import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./_context/AuthContext";
import SWRWrapper from "./_context/SWRWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TugasKita App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <SWRWrapper>
          <body className={inter.className}>{children}</body>
        </SWRWrapper>
      </AuthProvider>
    </html>
  );
}
